### ISSUE TITLE
JSON reporting seems to be broken

### ISSUE THREAD

**Issue by hmeine** [armijnhemel/binaryanalysis-ng#151]
I am getting this after setting `json = yes` in my config:
```
Traceback (most recent call last):
  File "bang-scanner", line 414, in <module>
    main(sys.argv)
  File "bang-scanner", line 374, in main
    JsonReporter(jsonfile).report(scanresult)
  File "/home/hmeine/tmp/tern-test/binaryanalysis-ng/src/JsonReporter.py", line 43, in report
    for a, h in fileresult.get_hashresult().items():
AttributeError: 'dict' object has no attribute 'get_hashresult'
```

**Comment by armijnhemel** [comment]
This particular reporting might (or might not) be retired in the near future, as I am currently working on separating unpacking, semantic scanning (scanning the contents of files) and reporting. I will put it on my TODO list. Thank you for reporting, it seems this one fell through the cracks.
