### ISSUE TITLE
"IndexError: list index out of range" and "Exceptions"

### ISSUE THREAD

**Issue by Ku100vEvgen** [armijnhemel/binaryanalysis-ng#33]
I'm trying a program to explore the possibilities of scanning

python3 ./bang-scanner -c ./bang.config -f ./gpt99_vfat16_sdb88.bin

and get errors

Process Process-2:
Traceback (most recent call last):
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 673, in processfile scanjob.check_for_signatures(unpacker)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 297, in check_for_signatures signature, offset)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/Unpacker.py", line 198, in try_unpack_file_for_signatures return bangsignatures.signaturetofunction[signature](fileresult, scanenvironment, offset, self.dataunpackdirectory)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/bangfilesystems.py", line 3032, in unpack_fat chainindex = clustervals[chainindex]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run self._target(*self._args, **self._kwargs)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 745, in processfile raise ScanJobError(scanjob, e)

ScanJob.ScanJobError: Exception for scanjob:
file:
    gpt99_vfat16_sdb88.bin
labels: root
Traceback (most recent call last):
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 673, in processfile scanjob.check_for_signatures(unpacker)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 297, in check_for_signatures signature, offset)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/Unpacker.py", line 198, in try_unpack_file_for_signatures return bangsignatures.signaturetofunction[signature](fileresult, scanenvironment, offset, self.dataunpackdirectory)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/bangfilesystems.py", line 3032, in unpack_fat chainindex = clustervals[chainindex]
IndexError: list index out of range

if interested, then this file https://cloud.mail.ru/public/5MZc/4GfiFTVwq

[gpt99_vfat16_sdb88.zip](https://github.com/armijnhemel/binaryanalysis-ng/files/3565623/gpt99_vfat16_sdb88.zip)

**Comment by armijnhemel** [comment]
thanks, this is indeed an error, will look at this soon.

Verstuurd vanaf mijn Eierfoon

**Comment by armijnhemel** [comment]
I have added a workaround in f0a70336d976778383f88c56a39fbbcb83a673d6 which will prevent the crash. This is not an ideal fix and I will look at a better solution in the future. Thanks for reporting!

**Comment by Ku100vEvgen** [comment]
it`s work. Thanks
