### ISSUE TITLE
uncompress exception

### ISSUE THREAD

**Issue by Ku100vEvgen** [armijnhemel/binaryanalysis-ng#34]
I'm trying a program to explore the possibilities of scanning

[kea@localhost src]$ python3 ./bang-scanner -c ./bang.config -f ./openwrt-18.06.1-brcm2708-bcm2710-rpi-3-squashfs-factory.img.gz

and get errors

Process Process-4:
Traceback (most recent call last):
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 673, in processfile scanjob.check_for_signatures(unpacker)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 297, in check_for_signatures signature, offset)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/Unpacker.py", line 198, in try_unpack_file_for_signatures return bangsignatures.signaturetofunction[signature](fileresult, scanenvironment, offset, self.dataunpackdirectory)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/bangunpack.py", line 12346, in unpack_compress p = subprocess.Popen(['uncompress'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__ restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'uncompress': 'uncompress'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run self._target(*self._args, **self._kwargs)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 745, in processfile raise ScanJobError(scanjob, e)
ScanJob.ScanJobError: Exception for scanjob:
file:
    openwrt-18.06.1-brcm2708-bcm2710-rpi-3-squashfs-factory.img.gz-gzip-1/openwrt-18.06.1-brcm2708-bcm2710-rpi-3-squashfs-factory.img
labels:

Traceback (most recent call last):
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 673, in processfile scanjob.check_for_signatures(unpacker)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/ScanJob.py", line 297, in check_for_signatures signature, offset)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/Unpacker.py", line 198, in try_unpack_file_for_signatures return bangsignatures.signaturetofunction[signature](fileresult, scanenvironment, offset, self.dataunpackdirectory)
  File "/home/kea/Загрузки/_soft/binaryanalysis/binaryanalysis-ng-master/src/bangunpack.py", line 12346, in unpack_compress p = subprocess.Popen(['uncompress'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__ restore_signals, start_new_session)
  File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'uncompress': 'uncompress'

if interested, then this file https://cloud.mail.ru/public/4Znn/sNB3zAYja
[openwrt-18.06.1-brcm2708-bcm2710-rpi-3-squashfs-factory.img.gz](https://github.com/armijnhemel/binaryanalysis-ng/files/3565684/openwrt-18.06.1-brcm2708-bcm2710-rpi-3-squashfs-factory.img.gz)

**Comment by armijnhemel** [comment]
looks like you missed installing the “ncompress” package. I think it was in the list of dependencies but I will check

Verstuurd vanaf mijn Eierfoon

**Comment by armijnhemel** [comment]
Have you managed to find the "uncompress" program? If you tell me which distribution you are using I can tell you which package to install.

**Comment by Ku100vEvgen** [comment]
Yes, I installed the "uncompress" program and it worked.

**Comment by Ku100vEvgen** [comment]
Yes, I installed the "uncompress" program and it worked.
