### ISSUE TITLE
bang-scanner file name too long error

### ISSUE THREAD

**Issue by itsallmathematics** [armijnhemel/binaryanalysis-ng#40]
When I run the bang-scanner I get:

```
Traceback (most recent call last):
  File "/usr/src/bang/src/ScanJob.py", line 689, in processfile
    scanjob.carve_file_data(unpacker)
  File "/usr/src/bang/src/ScanJob.py", line 481, in carve_file_data
    outfile = open(outfile_full, 'wb')
OSError: [Errno 36] File name too long: '/usr/src/bang/src/unpacked/bang-scan-zzd2vg9u/unpack/firmware.bin-0x00000076-lz4-1/unpacked-from-lz4-0x00def93d-synthesized-3/unpacked-0xdef93d-0x109123c-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900-0x00000000-synthesized-1/unpacked-0x0-0x2a1900'


Is there a way to prevent this?
```

**Comment by armijnhemel** [comment]
This actually looks like an off by one error somewhere. Do you have the firmware file available somewhere?

**Comment by timhemel** [comment]
Could it be that the program is adding a new ScanJob for a synthesized file and doing that over and over again, getting stuck in a loop. We could test this hypothesis by making an "unscannable" file that will trigger the synthesis of a new file.

**Comment by timhemel** [comment]
A parser that is succesful will extract the remainder of the file if it is longer than what it parsed. For parsers giving a zero length result this means the file is essentially copied, put on the scan queue and recognized again, ending up in an infinite loop. Non-positive parse lengths are now caught in the UnpackParser base class. However, putting this check in the code calling the UnpackParser may make it more robust.

**Comment by armijnhemel** [comment]
This was reported against the old unpacking framework. There is a new unpacking framework, where this error should no longer happen.
