### ISSUE TITLE
AttributeError: type object 'CyOpenGL.vector3' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by freedom-wy** [armijnhemel/binaryanalysis-ng#41]
```
(venv) freedom@freedom-virtual-machine:~/project/newbinaryscan/binaryanalysis-ng/src$ sudo /home/freedom/project/newbinaryscan/venv/bin/python bang-scanner -c bang.config -f test/testdata/unpackers/
Traceback (most recent call last):
  File "bang-scanner", line 55, in <module>
    from bangsignatures import maxsignaturesoffset
  File "/home/freedom/project/newbinaryscan/binaryanalysis-ng/src/bangsignatures.py", line 27, in <module>
    import bangandroid
  File "/home/freedom/project/newbinaryscan/binaryanalysis-ng/src/bangandroid.py", line 37, in <module>
    import bangunpack
  File "/home/freedom/project/newbinaryscan/binaryanalysis-ng/src/bangunpack.py", line 58, in <module>
    import snappy
  File "/home/freedom/project/newbinaryscan/venv/lib/python3.6/site-packages/snappy/__init__.py", line 7, in <module>
    from .SnapPy import (AbelianGroup, HolonomyGroup, FundamentalGroup,
  File "cython/core/basic.pyx", line 45, in init SnapPy
  File "/home/freedom/project/newbinaryscan/venv/lib/python3.6/site-packages/snappy/horoviewer.py", line 3, in <module>
    from .CyOpenGL import (HoroballScene, OpenGLOrthoWidget,
  File "opengl/CyOpenGL.pyx", line 38, in init CyOpenGL
AttributeError: type object 'CyOpenGL.vector3' has no attribute '__reduce_cython__'
(venv) freedom@freedom-virtual-machine:~/project/newbinaryscan/binaryanalysis-ng/src$ 
```

python3.6.9
ubuntu18.04

**Comment by armijnhemel** [comment]
Hm, it looks like snappy on Ubuntu 18.04 doesn't work correctly? I will put this on my TODO list (currently I am completely overloaded though).

**Comment by freedom-wy** [comment]
@armijnhemel 
python3.6.9
ubuntu18.04
snappy==2.7

another
Can you write a usage document？

**Comment by freedom-wy** [comment]
@armijnhemel 
Which version of operating system do you use？
and requirements.txt i need it.

**Comment by armijnhemel** [comment]
A lot of this is on my TODO list, but it will have to wait a bit as I am too busy, sorry. I am testing on Fedora 30 and 31 here.

**Comment by freedom-wy** [comment]
thank you
