### ISSUE TITLE
ImportError: cannot import name 'cpio_new_ascii'

### ISSUE THREAD

**Issue by yqbboy** [armijnhemel/binaryanalysis-ng#44]
When I execute the following command, I report the following error. How can I solve it?
--------------------------------------------------------------------------------
yqbboy@ubuntu:~/binaryanalysis-ng-master/src$ python3 bang-scanner -c bang.config -f /home/yq/samples/
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "bang-scanner", line 55, in <module>
    from bangsignatures import maxsignaturesoffset
  File "/home/secneo/binaryanalysis-ng-master/src/bangsignatures.py", line 487, in <module>
    extension_to_unpackparser = get_unpackers_for_extensions()
  File "/home/secneo/binaryanalysis-ng-master/src/bangsignatures.py", line 481, in get_unpackers_for_extensions
    for u in get_unpackers():
  File "/home/secneo/binaryanalysis-ng-master/src/bangsignatures.py", line 476, in get_unpackers
    pathlib.Path(os.path.dirname(parsers.__file__)), pathlib.Path('.'))
  File "/home/secneo/binaryanalysis-ng-master/src/bangsignatures.py", line 470, in _get_unpackers_recursive
    unpackers_root, full_module_path ))
  File "/home/secneo/binaryanalysis-ng-master/src/bangsignatures.py", line 461, in _get_unpackers_recursive
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/secneo/binaryanalysis-ng-master/src/parsers/archivers/cpio/UnpackParser.py", line 5, in <module>
    from . import cpio_new_ascii
ImportError: cannot import name 'cpio_new_ascii'

**Comment by timhemel** [comment]
You probably did not generate the parsers from the kaitai struct specification. A `make` should do the trick, but you will need
some software to build the parsers. In a release version that should not be needed, but we aren't there yet.

See https://github.com/armijnhemel/binaryanalysis-ng/blob/master/doc/kaitai-struct.md for instructions, or easier, use the docker container as described in the `README.md` file.
